findcorr/db/urls.py
from django.urls import path 
from . import views


app_name = 'db'

urlpatterns = [
    path('', views.corr_lst, name='corr_lst'),
    path('corr/<str:ticker_a>/<str:ticker_b>/', views.corr, name='corr'),
]

findcorr/findcorr/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('db.urls', namespace='db'))
]

findcorr/db/models.py
from django.db import models


class Candles(models.Model):
    candles_id = models.AutoField(primary_key=True)
    secid = models.CharField(max_length=20)
    pr_open = models.DateTimeField()
    pr_close = models.DateTimeField()
    pr_high = models.FloatField()
    pr_low = models.FloatField()
    val = models.FloatField()
    vol = models.FloatField()
    begin_dt = models.DateTimeField()
    end_dt = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'candles'
        ordering = ('candles_id',)
    
    def __str__(self):
        return self.secid


class Correlation(models.Model):
    id = models.AutoField(primary_key=True)
    ticker_A = models.CharField(max_length=20)
    ticker_B = models.CharField(max_length=20)
    correlation = models.FloatField()
    calc_dt = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'correlations'
        ordering = ('id',)
    
    def __str__(self):
        return f'{self.ticker_A}_{self.ticker_B}'


class Ticker(models.Model):
    id = models.AutoField(primary_key=True)
    ticker = models.CharField(max_length=20)
    name = models.CharField(max_length=255)
    sector = models.CharField(max_length=255)

    class Meta:
        managed = False
        db_table = 'decoding'
        ordering = ('id',)
    
    def __str__(self):
        return self.ticker


class CorrelationFull(models.Model):
    id = models.AutoField(primary_key=True)
    ticker_a = models.CharField(max_length=20)
    name_a = models.CharField(max_length=100)
    sector_a = models.CharField(max_length=50)
    ticker_b = models.CharField(max_length=20)
    name_b = models.CharField(max_length=100)
    sector_b = models.CharField(max_length=50)
    correlation = models.FloatField()
    status = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = 'correlations_full'
        ordering = ('id',)
        indexes = [
            models.Index(fields=['ticker_a', 'ticker_b']),
        ]
    
    def __str__(self):
        return f'{self.ticker_a}_{self.ticker_b}'


class CorrelationsDB(models.Model):
    description = models.CharField(max_length=255, null=False)

    class Meta:
        managed = False
        db_table = 'correlations'


class DecodingDB(models.Model):
    description = models.CharField(max_length=255, null=False)

    class Meta:
        managed = False
        db_table = 'decoding'


class CorrelationsFullDB(models.Model):
    description = models.CharField(max_length=255, null=False)

    class Meta:
        managed = False
        db_table = 'correlations_full'


class CandlesDB(models.Model):
    description = models.CharField(max_length=255, null=False)

    class Meta:
        managed = False
        db_table = 'candles'


class AlgoPackDBRouter(object):
    def db_for_read(self, model, **hints):
        if model in [Correlation, Ticker, CorrelationFull, Candles]:
            return 'algo_pack'
        return None

    def db_for_write(self, model, **hints):
        if model in [Correlation, Ticker, CorrelationFull, Candles]:
            return 'algo_pack'
        return None

findcorr/db/views.py
import json

from django.core.paginator import Paginator
from django.shortcuts import render, get_list_or_404
from django.http import HttpRequest, HttpResponse

from .models import CorrelationFull
from .dirt_correlation import get_df_to_plot


def round_corr(correlations: CorrelationFull) -> CorrelationFull:
        for group in correlations:
            if isinstance(group.correlation, float):
                group.correlation = round(group.correlation * 100)
        return correlations


def filter_industry(correlations: CorrelationFull, industry: str) -> CorrelationFull:
    correlations_filtered = []
    for group in correlations:
        group.sector_a, group.sector_b = group.sector_a.strip(), group.sector_b.strip()
        if (group.sector_a == industry) or (group.sector_b == industry):
            correlations_filtered.append(group)
    return correlations_filtered


def search_by_ticker(correlations: CorrelationFull, ticker: str) -> CorrelationFull:
    correlations_filtered = []
    for group in correlations:
        if (ticker in group.ticker_a.lower()) or (ticker in group.ticker_b.lower()):
            correlations_filtered.append(group)
    return correlations_filtered


def corr_lst(request: HttpRequest) -> HttpResponse:
    corr_list = round_corr(CorrelationFull.objects.all())

    industry = request.GET.get('industry', '').strip()
    if industry:
        corr_list = filter_industry(corr_list, industry)
    
    ticker = request.GET.get('q', '').strip()
    if ticker:
        corr_list = search_by_ticker(corr_list, ticker)

    sort = request.GET.get('sort', '')
    direction = request.GET.get('direction', 'asc')
    if sort:
        if direction == 'none':
            sort = 'id'
        if direction == 'desc':
            sort = '-' + sort
        corr_list = corr_list.order_by(sort)

    industries = CorrelationFull.objects.values_list('sector_a', flat=True).distinct()
    industries = sorted([ind.strip() for ind in set(industries) if ind.strip() != industry])
    
    paginator = Paginator(corr_list, 20)  # Show 20 correlations per page

    page_number = request.GET.get('page', '')
    correlations = paginator.get_page(page_number)

    return render(
        request, 
        'db/group/list.html', 
        {'industries': industries, 
         'correlations': correlations,
         'selected_industry': industry,}
    )


def corr(request: HttpRequest, ticker_a: str, ticker_b: str) -> HttpResponse:
    ticker_a, ticker_b = ticker_a.strip(), ticker_b.strip()
    corr_list = get_list_or_404(CorrelationFull, ticker_a=ticker_a, ticker_b=ticker_b)
    corr_list = round_corr(corr_list)

    df_plot = get_df_to_plot(ticker_a, ticker_b, '2021-12-01 00:00:00', '2023-12-01 00:00:00')
    lst_index = df_plot.index.tolist()
    ohlc_a = df_plot['OHLC_A_scaled'].tolist()
    ohlc_b = df_plot['OHLC_B_scaled'].tolist()
    spread_scaled = df_plot['spread_scaled'].tolist()
    # spread_medium = df_plot['spread_medium'].tolist()
    spread_medium = df_plot['spread_medium_line'].tolist()

    title = f"Масштабированная OHLC цена {ticker_a}  (тикер А) и {ticker_b} (тикер B), спред и лин. регрессия"

    return render(
        request, 
        'db/group/detail.html', 
        {'correlation': corr_list[0],
         'lst_index': json.dumps(lst_index),
         'ohlc_a': json.dumps(ohlc_a),
         'ohlc_b': json.dumps(ohlc_b),
         'spread_scaled': json.dumps(spread_scaled),
         'spread_medium': json.dumps(spread_medium),
         'title': title,
         'ticker_a': ticker_a,
         'ticker_b': ticker_b,}
    )

findcorr/db/templates/db/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru"></html>
<head>
    <meta charset="UTF-8">
    <title>Корреляция инструментов</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <style>
        .menu-item {
            display: block;
            width: 100%;
            padding: 10px;
            box-sizing: border-box;
            text-decoration: none;
            color: black;
            background-color: rgb(245, 246, 250);
            border-bottom: 1px solid #ccc;
        }

        .menu-item:hover {
            background-color: #ddd;
        }
    </style>
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>FindCorr</h1>
        </div>
        <div class="content", id="content">
            {% block content %}
            {% endblock %}
        </div>
        <div class="footer">
            <p>FindCorr© 2023</p>
    </div>
</body>
</html>

findcorr/db/templates/db/group/detail.html
{% extends 'db/base.html' %}

{% block content %}
    <div class="ticker-detail">
        <h1>{{ correlation.ticker_a }} & {{ correlation.ticker_b }}</h1>
        <p><b>Отрасль:</b> {{ correlation.sector_a }}</p>
        <p><b>Корреляция:</b> {{ correlation.correlation }}</p>
    </div>
    <div id="chart-container">
        <div id="myDiv"><!-- Plotly chart will be drawn inside this DIV --></div>
        <script>
            var lst_index = {{ lst_index|safe }};
            var ohlc_a = {{ ohlc_a|safe }};
            var ohlc_b = {{ ohlc_b|safe }};
            var spread_scaled = {{ spread_scaled|safe }};
            var spread_medium = {{ spread_medium|safe }};
        </script>
        <script>
            var trace1 = {
                name: '{{ correlation.ticker_a }}',
                x: lst_index, 
                y: ohlc_a,
                mode: 'lines',
                type: 'scatter',
                line: {
                    dash: 'dot',
                    color: 'rgba(0, 128, 0, 0.5)',
                    width: 2
                }
            };

            var trace2 = {
                name: '{{ correlation.ticker_b }}',
                x: lst_index, 
                y: ohlc_b, 
                mode: 'lines',
                type: 'scatter',
                line: {
                    color: 'rgba(255, 0, 0, 0.5)',
                    width: 2
                }
            };

            var trace3 = {
                name: 'Спред',
                x: lst_index, 
                y: spread_scaled, 
                mode: 'lines',
                type: 'scatter',
                line: {
                    dash: 'dashdot',
                    color: 'rgba(255, 128, 0, 0.5)',
                    width: 2
                }
            };

            var trace4 = {
                name: 'Лин. регрессия',
                x: lst_index, 
                y: spread_medium,  
                mode: 'lines',
                type: 'scatter',
                line: {
                    dash: 'solid',
                    color: 'rgba(0, 128, 255, 0.5)',
                    width: 2
                }
            };

            var data = [ trace1, trace2, trace3, trace4 ];

            var layout = {
                paper_bgcolor: 'rgb(245, 246, 250)',
                plot_bgcolor: 'rgb(245, 246, 250)',
                title: {
                    text: '{{ title }}',
                    font: {
                        weight: 'bold',
                        size: 24
                    },
                },
                height: 700,
                xaxis: {
                    showgrid: false,
                    zeroline: false
                },
                yaxis: {
                    showgrid: false,
                    zeroline: false,
                    showline: false,
                    showticklabels: false
                },
                legend: {
                    height: 100,
                    yref: 'paper',
                    font: {
                        size: 16
                    },
                }
            };

            Plotly.newPlot('myDiv', data, layout);
        </script>
    </div>
    <a href="{% url 'db:corr_lst' %}" class="back-button">Назад</a>
{% endblock %}

findcorr/db/templates/db/group/list.html
{% extends 'db/base.html' %}

{% block content %}
    <form method="GET" class="form-container">
        <div class="search-form">
            <input type="text" name="q" class="search-input" placeholder="Поиск по тикеру" value="{{ request.GET.q }}">
            <input type="submit" value="🔍">
        </div>
        <div class="dropdown">
            <label for="industry">Отрасль:</label>
            <select id="industry" name="industry" onchange="this.form.submit()">
                <option value="">
                    {% if request.GET.industry %}
                        {{ request.GET.industry }}
                    {% else %}
                        Все
                    {% endif %}
                </option>
                {% for industry in industries %}
                    {% if forloop.first and request.GET.industry %}
                        <option value="">Все</option>
                    {% endif %}
                    <option value="{{ industry }}" {% if request.GET.industry == industry %}selected{% endif %}>{{ industry }}</option>
                {% endfor %}
            </select>
            <div class="ticker-count-info">Доступно: {{ correlations.paginator.count }}</div>
        </div>
    </form>
    <table>
        <tr>
            <th><a href="?sort=ticker_a&direction={% if request.GET.sort == 'ticker_a' and request.GET.direction == 'asc' %}desc{% else %}asc{% endif %}">Тикер A</a></th>
            <th><a href="?sort=name_a&direction={% if request.GET.sort == 'name_a' and request.GET.direction == 'asc' %}desc{% else %}asc{% endif %}">Название A</a></th>
            <th><a href="?sort=sector_a&direction={% if request.GET.sort == 'sector_a' and request.GET.direction == 'asc' %}desc{% else %}asc{% endif %}">Отрасль A</a></th>
            <th><a href="?sort=ticker_b&direction={% if request.GET.sort == 'ticker_b' and request.GET.direction == 'asc' %}desc{% else %}asc{% endif %}">Тикер Б</a></th>
            <th><a href="?sort=name_b&direction={% if request.GET.sort == 'name_b' and request.GET.direction == 'asc' %}desc{% else %}asc{% endif %}">Название Б</a></th>
            <th><a href="?sort=sector_b&direction={% if request.GET.sort == 'sector_b' and request.GET.direction == 'asc' %}desc{% else %}asc{% endif %}">Отрасль Б</a></th>
            <th><a href="?sort=correlation&direction={% if request.GET.sort == 'correlation' and request.GET.direction == 'asc' %}desc{% else %}asc{% endif %}">Корреляция</a></th>
            <th><a href="?sort=status&direction={% if request.GET.sort == 'status' and request.GET.direction == 'asc' %}desc{% else %}asc{% endif %}">Статус</a></th>
        </tr>
        {% for group in correlations %}
        <tr>
            <td class="bold">
                <a href="{% url 'db:corr' ticker_a=group.ticker_a ticker_b=group.ticker_b %}">
                    {{ group.ticker_a }}
                </a>
            </td>
            <td>{{ group.name_a }}</td>
            <td>{{ group.sector_a }}</td>
            <td class="bold">
                <a href="{% url 'db:corr' ticker_a=group.ticker_a ticker_b=group.ticker_b %}">
                    {{ group.ticker_b }}
                </a>
            </td>
            <td>{{ group.name_b }}</td>
            <td>{{ group.sector_b }}</td>
            <td>{{ group.correlation }}</td>
            <td class="status {% if group.status == 'Слабая' %}weak{% elif group.status == 'Средняя' %}medium{% elif group.status == 'Сильная' %}strong{% endif %}">{{ group.status }}</td>
        </tr>
        {% endfor %}
    </table>
    <div class="pagination">
        {% if correlations.has_previous %}
            <a class="pagination-button" href="?page={{ correlations.previous_page_number }}&industry={{ selected_industry }}">←</a>
        {% endif %}
    
        {% for i in correlations.paginator.page_range %}
            {% if correlations.number == i %}
                <a class="pagination-button current" href="?page={{ i }}&industry={{ selected_industry }}">{{ i }}</a>
            {% elif i > correlations.number|add:"-5" and i < correlations.number|add:"5" %}
                <a class="pagination-button" href="?page={{ i }}&industry={{ selected_industry }}">{{ i }}</a>
            {% elif i == 1 %}
                <a class="pagination-button" href="?page={{ i }}&industry={{ selected_industry }}">{{ i }}</a>
                {% if correlations.number > 6 %}
                    <span class="pagination-ellipsis">...</span>
                {% endif %}
            {% elif i == correlations.paginator.num_pages %}
                {% if correlations.number|add:"5" < correlations.paginator.num_pages %}
                    <span class="pagination-ellipsis">...</span>
                {% endif %}
                <a class="pagination-button" href="?page={{ i }}&industry={{ selected_industry }}">{{ i }}</a>
            {% endif %}
        {% endfor %}
    
        {% if correlations.has_next %}
        <a class="pagination-button" href="?page={{ correlations.next_page_number }}&industry={{ selected_industry }}">→</a>
        {% endif %}
    </div>
{% endblock %}